export const FETCHING_DETAIL_MARKET = "FETCHING_DETAIL_MARKET";
export const FETCHING_DETAIL_MARKET_SUCCESS = "FETCHING_DETAIL_MARKET_SUCCESS";
export const FETCHING_DETAIL_MARKET_ERROR = "FETCHING_DETAIL_MARKET_ERROR";
